PP5_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profiles/', include('profiles.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bag/urls.py
from django.contrib import admin
from django.urls import path
from  .import views

urlpatterns = [
    path('', views.view_bag, name="view_bag"),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

profiles/urls.py
from django.urls import path
from django.conf import settings
from .views import CustomLoginView, SignUpView, Profile, logout_view, cancel_workshop
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('profile/', views.profile, name='profile'),
]

profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from products.models import Product
from django.db.models.signals import post_save
from django.dispatch import receiver

def user_directory_path(instance, filename):
    return f'user_{instance.user.id}/{filename}'

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to=user_directory_path, null=True, blank=True)
    school_details = models.TextField(blank=True)
    students_info = models.TextField(blank=True)
    phone_number = models.CharField(max_length=15, blank=True)
    booked_workshops = models.ManyToManyField(Product, blank=True)

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    else:
        instance.profile.save()

profiles/forms.py
# forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Provide a valid email address.')
    full_name = forms.CharField(max_length=100, required=True, help_text='Required.')
    phone_number = forms.CharField(max_length=15, required=True, help_text='Required.')

    class Meta:
        model = User
        fields = ('username', 'email', 'full_name', 'phone_number', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.full_name = self.cleaned_data['full_name']
        user.phone_number = self.cleaned_data['phone_number']
        if commit:
            user.save()  # Save the user instance first
            Profile.objects.create(user=user)
        return user

class ProfileForm(forms.ModelForm):
   class Meta:
       model = Profile
       fields = ['profile_picture','school_details', 'students_info',]
       widgets = {
           'school_details': forms.Textarea(attrs={'placeholder': "Please enter your school's details here"}),
           'students_info': forms.Textarea(attrs={
            'placeholder':
            'Please enter the cycle and level you primarily teach here. You can also add any other information.'}),
        }

profiles/views.py
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.views import LoginView
from .forms import CustomUserCreationForm, ProfileForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from checkout.models import OrderLineItem
from .models import Profile
from products.models import Product, Booking
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def profile(request):
    profile = Profile.objects.get(user=request.user)
    bookings = Booking.objects.filter(user=request.user)
    return render(request, 'profiles/profile.html', {'profile': profile, 'bookings': bookings})



class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('profile')  # Redirect to profile page after successful signup
    template_name = 'registration/signup.html'

    def form_valid(self, form):
        user = form.save()  # This will save both User and Profile due to form's save method
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(username=user.username, password=raw_password)
        if user is not None:
            login(self.request, user)
            messages.success(self.request, 'Account created successfully!')
            return redirect(self.success_url)
        else:
            messages.error(self.request, 'Failed to authenticate. Please try logging in.')
            return redirect('signup')

class CustomLoginView(LoginView):
    template_name = 'registration/login.html'

    def get_success_url(self):
        return reverse_lazy('profile')  # Redirect to profile page after login


@login_required
def edit_profile(request):
    profile, created = Profile.objects.get_or_create(user=request.user)

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your profile details have been saved.')
            return redirect('edit_profile')  # Redirect after successful form submission
        else:
            messages.error(request, 'Please correct the errors below.')
    else:
        form = ProfileForm(instance=profile)

    booked_workshops = OrderLineItem.objects.filter(user=request.user).select_related('product')

    context = {
        'profile': profile,
        'form': form,
        'booked_workshops': booked_workshops,
    }

    return render(request, 'profiles/profile.html', context)


@login_required
def cancel_workshop(request, workshop_id):
    workshop = get_object_or_404(Product, pk=workshop_id)
    user = request.user

    # Find the corresponding OrderLineItem
    booked_workshop = get_object_or_404(OrderLineItem, user=user, product=workshop)

    # Remove the workshop from the user's booked workshops
    user.profile.booked_workshops.remove(workshop)

    # Delete the OrderLineItem instance
    booked_workshop.delete()

    messages.success(request, f'You have successfully canceled the workshop: {workshop.name}.')
    return redirect('profile')


def logout_view(request):
    logout(request)
    return redirect('login')

profiles/templates/profiles/profile.html
{% extends 'base.html' %}

{% load static %}
{% block extra_head %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <script src="{% static 'js/edit_profile.js' %}"></script>
{% endblock %}

{% block content %}
<div class="main-content">
<div class="profile-and-workshops">
    <h1>Profile</h1>
    <div class="details-form-container">
        <div class="profile-section">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="profile-header">
                    <img id="profile-photo" src="{% if user.profile.profile_picture %}{{ user.profile.profile_picture.url }}{% else %}{% static 'media/../../../../PP4MWV2/static/media/default_profile.jpg' %}{% endif %}" alt="Profile Photo" class="profile-photo"><br>
                    <label for="id_profile_picture" class="profile-picture-label">Change profile picture</label><br>
                    <input type="file" id="id_profile_picture" name="profile_picture" class="hidden-file-input">
                </div>

                <div class="user-details">
                    <p><strong>Email:</strong> {{ request.user.email }}</p>
                </div>

                <div class="profile-form">
                    <div class="form-group">
                        <label for="id_school_details"><strong>School Details:</strong></label>
                        {{ form.school_details }}
                    </div>
                    <div class="form-group">
                        <label for="id_students_info"><strong>My students are:</strong></label>
                        {{ form.students_info }}
                    </div>
                    <button type="submit" class="save-changes">Save changes</button>
                </div>
            </form>
        </div>
    </div>

    <h2>Booked Workshops</h2>
    <div class="booked-workshops">
        {% for booked_workshop in booked_workshops %}
            <div class="workshop">
                <div class="workshop-details d-flex">
                    <div class="workshop-image">
                        <img src="{{ booked_workshop.workshop.image.url }}" alt="Workshop Image">
                    </div>
                    <div class="item-details">
                        <h3>{{ booked_workshop.workshop.title }}</h3>
                        <p>Price: €{{ booked_workshop.workshop.price }}</p>
                        <p>Date and Time: {{ booked_workshop.date_time }}</p>
                        <p>Quantity: {{ booked_workshop.quantity }}</p>
                    </div>
                </div>
                <div class="workshop-action">
                    <form action="{% url 'cancel_workshop' booked_workshop.workshop.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="cancel-button btn btn-danger">Cancel Workshop</button>
                    </form>
                </div>
            </div>
        {% empty %}
            <p>No workshops booked yet.</p>
        {% endfor %}
    </div>

    {% if message %}
    <div class="alert alert-success mt-3" role="alert">
        {{ message }}
    </div>
    {% endif %}
</div>
</div>
{% endblock %}